export const APP_ROUTES = {
  login: "/login",
  adminLogin: "/admin/login",
  home: "/",
  about: "/about",
  contact: "/contact",
  donation: "/donation",
  hallOfHonor: "/hall-of-honor",
  upload: "/upload",
  history: "/history",
  assessment: "/assessment",
  infographic: "/infographic",
  settings: "/settings",
  admin: "/admin",
  adminUsers: "/admin/users",
} as const;
